#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"

if [ -d "venv" ]; then
  source venv/bin/activate
fi

if [ ! -f ".env" ]; then
  echo ".env not found. Run ./install or copy .env.sample to .env"
  exit 1
fi

source .env

python main.py
