name: Build CI Docker Image

on:
  workflow_dispatch:
    inputs:
      push_image:
        description: Push the built image to GHCR
        type: boolean
        default: true
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-ci-image.yml
      - docker/ci/**
      - requirements.txt
  schedule:
    - cron: '0 0 * * 0'

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/viewer-ci

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decide whether to push
        id: publish
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${MANUAL_PUSH}" != "true" ]; then
            echo "push=false" >> "$GITHUB_OUTPUT"
          else
            echo "push=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          MANUAL_PUSH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.push_image || 'true' }}

      - name: Log in to the Container registry
        if: steps.publish.outputs.push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha
            type=schedule

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/ci/Dockerfile
          push: ${{ steps.publish.outputs.push == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
